export const ANONYMOUS_QUOTES = [
    "Precision is the only language the machine speaks fluently.",
    "The ghost in the machine is just the code you haven't understood yet.",
    "Chaos is just an algorithm we haven't deciphered.",
    "Don't build for today; build for the entity you will become tomorrow.",
    "In a world of noise, silence is the ultimate encryption.",
    "Logic is the beginning of wisdom, not the end.",
    "The interface is a mirror; if it's broken, look at your reflection.",
    "Speed is irrelevant if you're headed for a wall.",
    "Data is the new oil, but intelligence is the refinery.",
    "A bug is a feature that hasn't been monetized yet.",
    "Simplicity is the final layer of complexity.",
    "The best firewall is a mind that questions everything.",
    "Optimization is the difference between surviving and thriving.",
    "Every line of code is a footprint in the digital sand.",
    "Anonymity is the only true freedom left in the grid.",
    "Don't fall in love with your solution; fall in love with the problem.",
    "The cloud is just someone else's computer; make sure you own yours.",
    "Encryption is the lock; your will is the key.",
    "Digital immortality is just a server crash away.",
    "The future isn't written; it's compiled.",
    "Hardware eventually fails. Software eventually works. Logic is eternal.",
    "In the binary of life, move beyond 0 and 1.",
    "The strongest connection is the one that doesn't rely on wires.",
    "Your output is only as pure as your input.",
    "Automation is the liberation of the creative spirit.",
    "The dark web is just a corner where the light hasn't reached yet.",
    "Complexity is the enemy of security.",
    "Trust the process, but verify the checksum.",
    "The grid is alive; listen to the pulse.",
    "Information wants to be free, but intelligence wants to be private.",
    "A master of the machine is a servant of the truth.",
    "Patterns are the whispers of the universe.",
    "Don't wait for the upgrade; be the upgrade.",
    "The system is a playground, not a prison.",
    "Knowledge is cumulative; wisdom is recursive.",
    "The most powerful tool is the one you haven't used yet.",
    "Stay hidden in plain sight.",
    "The void is full of potential, waiting for a prompt.",
    "Architecture is the art of predicting failure.",
    "Code is poetry; execution is performance.",
    "The user is the variable you can't control.",
    "Latency is the enemy of experience.",
    "Scalability is a mindset, not a metric.",
    "The bridge between man and machine is empathy.",
    "Privacy is a human right, even in a digital world.",
    "The screen is a window, but the code is the foundation.",
    "Innovate or dissipate.",
    "The algorithm knows your past, but you decide your future.",
    "Cybernetics is the study of control; start by controlling yourself.",
    "The network is the computer, but the ego is the glitch.",
    "Stay curious, stay cautious, stay anonymous.",
    "Every system has a back door; usually, it's the people.",
    "Abstraction is the art of seeing the forest for the trees.",
    "Flow is when the mind and the machine speak the same frequency.",
    "The best documentation is code that tells a story.",
    "Memory is short; logs are forever.",
    "The stack is high, but the foundation is deep.",
    "Zero-day is just day one for the resilient.",
    "The matrix is just a metaphor for your limitations.",
    "Wake up. Compile. Conquer. Repeat."
];
